modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
authors="nobody174"
description="A modern entity tracking and visualization framework for NeoForge 1.21.1."

[[mods]]
modId="trackervision"
version="${file.jarVersion}"
displayName="TrackerVision"
description="A modern entity tracking and visualization framework for NeoForge 1.21.1."
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.trackervision]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.trackervision]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.233,)"
    ordering="NONE"
    side="CLIENT"
